"use client";

import * as Lucide from "lucide-react";

export const UTILITY_ICONS: Record<string, Lucide.LucideIcon> = {
  wifi: Lucide.Wifi,
  power: Lucide.Power,
  backupPower: Lucide.BatteryCharging,
  water: Lucide.Droplets,
  trash: Lucide.Trash2,
  trash_bin: Lucide.Trash2,
  mail: Lucide.Mail,
  phone: Lucide.Mail,
  internet: Lucide.Cpu,
  computer: Lucide.Cpu,
  office: Lucide.Building2,
  store: Lucide.Building2,
  storefront: Lucide.Building2,
  meeting: Lucide.Users,
  work: Lucide.Briefcase,
  printer: Lucide.Printer,
  pos: Lucide.Printer,
  gym: Lucide.Dumbbell,
  bike: Lucide.Bike,
  parking: Lucide.Package,
  spa: Lucide.Heart,
  entertainment: Lucide.Smile,
  bar: Lucide.GlassWater,
  restaurant: Lucide.Utensils,
  book: Lucide.Book,
  library: Lucide.BookOpen,
  users: Lucide.Users,
  star: Lucide.Star,
  tag: Lucide.Star,
  calendar: Lucide.BookOpen,
  child: Lucide.Users,
  bell: Lucide.Bell,
  concierge: Lucide.UserCheck,
  maintenance: Lucide.Wrench,
  cleaning: Lucide.Wrench,
  map_pin: Lucide.MapPin,
  doorClosed: Lucide.DoorClosed,
};
